version: "3"

services:
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    ports:
      - "8080:8080"
  db:
    image: arm64v8/postgres:11.18-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - user-db:/var/lib/postgresql/data

volumes:
  user-db: