version: "3"
services:
  consul:
    image: arm64v8/consul:1.13.3
    environment:
      CONSUL_BIND_INTERFACE: "eth0"
    command: "agent -server -dev -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    ports:
      - "8500:8500"
  mqtt:
    image: arm64v8/eclipse-mosquitto:2.0.15
    ports:
      - "1883:1883"
      - "9001:9001"
  zookeeper:
    image: quay.io/strimzi/kafka:0.22.1-kafka-2.7.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
  kafka:
    image: quay.io/strimzi/kafka:0.22.1-kafka-2.7.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  schema-registry:
    image: apicurio/apicurio-registry-mem:2.4.1.Final
    ports:
      - "8001:8080"
    depends_on:
      - kafka
    environment:
      QUARKUS_PROFILE: prod
